// <auto-generated />
using System;
using CAM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CAM.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("CAM.Core.Entities.Aircraft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<bool>("IsTwin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("SerialNum")
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("CAM.Core.Entities.DiscrepancyAggregate.Discrepancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFinalized")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SquawkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkStatusId");

                    b.ToTable("Discrepancies");
                });

            modelBuilder.Entity("CAM.Core.Entities.DiscrepancyAggregate.DiscrepancyPart", b =>
                {
                    b.Property<int>("DiscrepancyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Qty")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscrepancyId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("DiscrepancyParts");
                });

            modelBuilder.Entity("CAM.Core.Entities.DiscrepancyAggregate.LaborRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscrepancyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LaborInHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscrepancyId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LaborRecords");
                });

            modelBuilder.Entity("CAM.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificationNum")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CAM.Core.Entities.Part", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("CataloguePartNumber")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("CurrentStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(600);

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageThumbPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDiscontinued")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<int>("PartCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceIn")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtySoldToDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("PartCategoryId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("CAM.Core.Entities.PartCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("PartCategories");
                });

            modelBuilder.Entity("CAM.Core.Entities.Squawk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateResolved")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsGroundable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pilot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<string>("Resolution")
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<int>("StatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("StatusId");

                    b.ToTable("Squawks");
                });

            modelBuilder.Entity("CAM.Core.Entities.SquawkStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SquawkStatuses");
                });

            modelBuilder.Entity("CAM.Core.Entities.Times", b =>
                {
                    b.Property<string>("AircraftId")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<int>("AirTime")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AircraftTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cycles")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Engine1Total")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Engine2Total")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hobbs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prop1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prop2")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tach1")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tach2")
                        .HasColumnType("TEXT");

                    b.HasKey("AircraftId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("CAM.Core.Entities.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFinalized")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.Property<int>("WorkStatusId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkStatusId");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("CAM.Core.Entities.WorkStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("WorkStatuses");
                });

            modelBuilder.Entity("CAM.Core.Entities.Aircraft", b =>
                {
                    b.HasOne("CAM.Core.Entities.Times", "Times")
                        .WithOne("Aircraft")
                        .HasForeignKey("CAM.Core.Entities.Aircraft", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAM.Core.Entities.DiscrepancyAggregate.Discrepancy", b =>
                {
                    b.HasOne("CAM.Core.Entities.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.HasOne("CAM.Core.Entities.WorkOrder", null)
                        .WithMany("Discrepancies")
                        .HasForeignKey("WorkOrderId");

                    b.HasOne("CAM.Core.Entities.WorkStatus", "WorkStatus")
                        .WithMany()
                        .HasForeignKey("WorkStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAM.Core.Entities.DiscrepancyAggregate.DiscrepancyPart", b =>
                {
                    b.HasOne("CAM.Core.Entities.DiscrepancyAggregate.Discrepancy", "Discrepancy")
                        .WithMany("DiscrepancyParts")
                        .HasForeignKey("DiscrepancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAM.Core.Entities.Part", "Part")
                        .WithMany("DiscrepancyParts")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAM.Core.Entities.DiscrepancyAggregate.LaborRecord", b =>
                {
                    b.HasOne("CAM.Core.Entities.DiscrepancyAggregate.Discrepancy", null)
                        .WithMany("LaborRecords")
                        .HasForeignKey("DiscrepancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAM.Core.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAM.Core.Entities.Part", b =>
                {
                    b.HasOne("CAM.Core.Entities.PartCategory", "PartCategory")
                        .WithMany()
                        .HasForeignKey("PartCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAM.Core.Entities.Squawk", b =>
                {
                    b.HasOne("CAM.Core.Entities.Aircraft", "Aircraft")
                        .WithMany("Squawks")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CAM.Core.Entities.SquawkStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CAM.Core.Entities.WorkOrder", b =>
                {
                    b.HasOne("CAM.Core.Entities.WorkStatus", "WorkStatus")
                        .WithMany()
                        .HasForeignKey("WorkStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
